name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-11
    env:
      #DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer

    steps:
    - name: Show environments
      run: |
        sw_vers
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Lint Swift
      run: |
        swiftlint
    - name: Build Framework
      run: |
        swift build
